# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("KacstLetter")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(398, 490, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.l_email = QtWidgets.QLabel(self.centralwidget)
        self.l_email.setGeometry(QtCore.QRect(140, 250, 71, 17))
        self.l_email.setObjectName("l_email")
        self.l_password = QtWidgets.QLabel(self.centralwidget)
        self.l_password.setGeometry(QtCore.QRect(90, 300, 121, 20))
        self.l_password.setObjectName("l_password")
        self.i_email = QtWidgets.QLineEdit(self.centralwidget)
        self.i_email.setGeometry(QtCore.QRect(260, 250, 261, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.i_email.setFont(font)
        self.i_email.setObjectName("i_email")
        self.i_password = QtWidgets.QLineEdit(self.centralwidget)
        self.i_password.setGeometry(QtCore.QRect(260, 300, 261, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.i_password.setFont(font)
        self.i_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.i_password.setObjectName("i_password")
        self.computerCamera = QtWidgets.QRadioButton(self.centralwidget)
        self.computerCamera.setGeometry(QtCore.QRect(150, 60, 231, 23))
        self.computerCamera.setChecked(True)
        self.computerCamera.setObjectName("computerCamera")
        self.video = QtWidgets.QRadioButton(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(150, 110, 112, 23))
        self.video.setObjectName("video")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 421, 21))
        self.label.setObjectName("label")
        self.videoFrame = QtWidgets.QWidget(self.centralwidget)
        self.videoFrame.setEnabled(True)
        self.videoFrame.setGeometry(QtCore.QRect(210, 100, 541, 91))
        self.videoFrame.setObjectName("videoFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.videoFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 11, 481, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.showVideoBox = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.showVideoBox.setContentsMargins(0, 0, 0, 0)
        self.showVideoBox.setObjectName("showVideoBox")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.showVideoBox.addWidget(self.label_2)
        self.videoName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoName.sizePolicy().hasHeightForWidth())
        self.videoName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.videoName.setFont(font)
        self.videoName.setObjectName("videoName")
        self.showVideoBox.addWidget(self.videoName)
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setEnabled(True)
        self.picture.setGeometry(QtCore.QRect(0, -20, 961, 611))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("background.jpg"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 200, 541, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 360, 521, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 410, 71, 20))
        self.label_5.setObjectName("label_5")
        self.receiveEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.receiveEmail.setGeometry(QtCore.QRect(262, 400, 261, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.receiveEmail.setFont(font)
        self.receiveEmail.setObjectName("receiveEmail")
        self.picture.raise_()
        self.pushButton.raise_()
        self.l_email.raise_()
        self.l_password.raise_()
        self.i_email.raise_()
        self.i_password.raise_()
        self.computerCamera.raise_()
        self.video.raise_()
        self.label.raise_()
        self.videoFrame.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.receiveEmail.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 5, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.statusBar.setPalette(palette)
        self.statusBar.setStyleSheet("background-color: rgb(2, 5, 49);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion detector"))
        self.pushButton.setStatusTip(_translate("MainWindow", "Start motion detection."))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.l_email.setStatusTip(_translate("MainWindow", "Email account from which the notification is sent.s"))
        self.l_email.setText(_translate("MainWindow", "Email:"))
        self.l_password.setStatusTip(_translate("MainWindow", "Password to email account from which the notification is sent."))
        self.l_password.setText(_translate("MainWindow", "Password:"))
        self.i_email.setStatusTip(_translate("MainWindow", "Email account from which the notification is sent."))
        self.i_email.setPlaceholderText(_translate("MainWindow", "Enter email"))
        self.i_password.setStatusTip(_translate("MainWindow", "Password to email account from which the notification is sent."))
        self.i_password.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.computerCamera.setStatusTip(_translate("MainWindow", "It will detect motion on the recording provided by your computer camera."))
        self.computerCamera.setText(_translate("MainWindow", "Computer camera"))
        self.video.setStatusTip(_translate("MainWindow", "You give the name of the video on your computer. It is important that is in the same directory as program."))
        self.video.setText(_translate("MainWindow", "Video"))
        self.label.setText(_translate("MainWindow", "Choose how you enter the recording:"))
        self.label_2.setText(_translate("MainWindow", "Name of the video:"))
        self.videoName.setPlaceholderText(_translate("MainWindow", "Enter the name of the video"))
        self.label_3.setText(_translate("MainWindow", "Account from which you send the notification:"))
        self.label_4.setText(_translate("MainWindow", "Account where the notification is received:"))
        self.label_5.setStatusTip(_translate("MainWindow", "Email where the notice about motion will be sent."))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.receiveEmail.setStatusTip(_translate("MainWindow", "Email where the notice about motion will be sent."))
        self.receiveEmail.setPlaceholderText(_translate("MainWindow", "Enter email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

